# Generated by Django 2.1 on 2018-08-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='buildV',
            new_name='FC',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='function',
            new_name='case_pass_rate',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='monkey',
            new_name='running_time',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='stress',
            new_name='test_description',
        ),
        migrations.RemoveField(
            model_name='prj',
            name='description',
        ),
        migrations.RemoveField(
            model_name='version',
            name='name',
        ),
        migrations.AddField(
            model_name='prj',
            name='dut_id',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AddField(
            model_name='prj',
            name='sku_id',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AddField(
            model_name='result',
            name='result_url',
            field=models.CharField(default='abc', max_length=70),
        ),
        migrations.AddField(
            model_name='result',
            name='type_id',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AddField(
            model_name='version',
            name='lastupdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='sw_build',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='version',
            name='sw_version',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
