# Generated by Django 2.1 on 2018-08-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWT', '0003_auto_20180831_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='lastupdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='version',
            name='sw_build',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='version',
            name='sw_version',
            field=models.CharField(max_length=100),
        ),
    ]
