# Generated by Django 2.1 on 2018-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWT', '0005_auto_20180831_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-lastupdate']},
        ),
        migrations.AlterField(
            model_name='result',
            name='FC',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='content',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
