# Generated by Django 2.1 on 2018-09-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWT', '0006_auto_20180906_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='case_pass_rate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_url',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='running_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='test_description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='type_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
