# Generated by Django 2.1 on 2018-09-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWT', '0007_auto_20180906_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prj',
            name='id',
        ),
        migrations.AlterField(
            model_name='prj',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
