# Generated by Django 2.1 on 2018-09-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWT', '0009_auto_20180907_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
