# Generated by Django 2.1 on 2018-09-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWT', '0010_auto_20180907_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
